/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java

    pmd
    id("org.owasp.dependencycheck")
    checkstyle
    jacoco
    id("com.github.ben-manes.versions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()

    finalizedBy(tasks.jacocoTestReport)
    finalizedBy(tasks.jacocoTestCoverageVerification)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
}

tasks.jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = "0.5".toBigDecimal()
            }
        }
    }
}

tasks.check {
    dependsOn(tasks.dependencyUpdates)
}

tasks.withType<Pmd> {
    isConsoleOutput = true
    rulesMinimumPriority.set(5)
    ruleSetFiles = files("$rootDir/config/pmd/custom_rules.xml")
    ruleSets = listOf()
}

tasks.getByName<Pmd>("pmdTest") {
    ruleSets = listOf()
    ruleSetFiles = files("$rootDir/config/pmd/custom_test_rules.xml")
}

configure<CheckstyleExtension> {
    toolVersion = "8.40"
    isIgnoreFailures = false
    maxWarnings = 0
}