/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
    pmd
    id("org.owasp.dependencycheck")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.9")
    }

    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.1")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

//checkstyle {
//    maxWarnings = 0
//}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<Pmd> {
    isConsoleOutput = true
    rulesMinimumPriority.set(5)
    ruleSetFiles = files("$rootDir/config/pmd/custom_rules.xml")
    ruleSets = listOf()
}

tasks.getByName<Pmd>("pmdTest") {
    ruleSets = listOf()
    ruleSetFiles = files("$rootDir/config/pmd/custom_test_rules.xml")
}